In [1]:
import numpy as np

#### Q1. Write a functions that takes in an n-dimensional array and converts that to a 1d array without using the `.reshape()` method.

In [ ]:
def linearize(nd_arr):
    return nd_arr

##### Testcases

In [8]:
linearize(np.array([[1, 2, 3, 4]]))

# Expected Output : [1, 2, 3, 4]

1
2
3
4


array([1, 2, 3, 4])

In [9]:
linearize(np.array([1, 2, 3, 4]))

# Expected Output : array([1, 2, 3, 4])

1
2
3
4


array([1, 2, 3, 4])

In [10]:
linearize(np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

# Expected Output : array([1, 2, 3, 4, 5, 6, 7, 8])

1
2
3
4
5
6
7
8


array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
linearize(np.array([[[0]]]))

# Expected Output : [0]

0


array([0])

In [12]:
linearize(np.array([[], [], []]))

# Expected Output : []

array([], dtype=float64)