## About Numpy

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

Although Python lists are excellent, general-purpose containers. They can be `heterogeneous`, meaning that they can contain elements of a variety of types.

On the other hand, most NumPy arrays have some restrictions. For instance:
- They must be `homogeneous`, i.e. All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be `rectangular`, not jagged; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks.

## Installing and Importing

To install Numpy as a package:

```shell
>> pip install numpy
```

To import numpy:

In [1]:
import numpy as np

## Initialising numpy arrays

#### Initialising arrays from Python sequences

One way to initialize an array is using a Python sequence, such as a `list` or a `tuple`.
to initialize an array from a sequence, we use `np.array()`.

We can also `np.array()` on another array to make a new copy of it.

In [2]:
myList = [5, 2, 1, 4]
print(type(myList), myList)
myTuple = (5, 2, 1, 4)
print(type(myTuple), myTuple)

print()
fromTuple = np.array(myTuple)
print(type(fromTuple), fromTuple)
fromList = np.array(myList)
print(type(fromList), fromList)
fromArray = np.array(fromList)
print(type(fromArray), fromArray)

a = np.array(fromArray, 'int16')
print(f"\narray = {a}")
print(f"dimension            = {a.ndim}")
print(f"shape                = {a.shape}")
print(f"data type            = {a.dtype}")
print(f"no of elements       = {len(a)}")
print(f"no of elements       = {a.size}")
print(f"size of each element = {a.itemsize}")
print(f"size of array        = {a.size * a.itemsize}")
print(f"size of array        = {a.nbytes}")

<class 'list'> [5, 2, 1, 4]
<class 'tuple'> (5, 2, 1, 4)

<class 'numpy.ndarray'> [5 2 1 4]
<class 'numpy.ndarray'> [5 2 1 4]
<class 'numpy.ndarray'> [5 2 1 4]

array = [5 2 1 4]
dimension            = 1
shape                = (4,)
data type            = int16
no of elements       = 4
no of elements       = 4
size of each element = 2
size of array        = 8
size of array        = 8


we can also initialize a multi-dimensional array using a `nested list` or `nested tuple`.

In [3]:
nested = np.array(
    [
        [9.1, 8.2, 7.3],
        [3.7, 2.8, 1.9]
    ]
)
print(nested)
print(f"dimension = {nested.ndim}")
print(f"shape     = {nested.shape}")
print(f"length    = {len(nested)}")
print(f"size      = {nested.size}")

[[9.1 8.2 7.3]
 [3.7 2.8 1.9]]
dimension = 2
shape     = (2, 3)
length    = 2
size      = 6


we can also initialize an array using a `list comprehension`.

In [4]:
myList = [i for i in range(0, 40, 2)]
print(myList)

myArray = np.array( [i for i in range(0, 40, 2)] )
print(myArray)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


#### Special constructors in Numpy

`np.arange()` creates an array with regularly spaced values within a given interval.
It's similar to Python's built-in `range()`, but it returns a NumPy array and supports decimal (float) steps.

In [5]:
arr = np.arange(5)
print(f"arr = {arr}")

arr = np.arange(2, 10)
print(f"arr = {arr}")

arr = np.arange(2, 10, 2)
print(f"arr = {arr}") 

arr = np.arange(0, 1, 0.2)
print(f"arr = {arr}")

arr = np.arange(1, 6, 0.5, dtype='int8')
print(f"arr = {arr}") 

arr = [0 1 2 3 4]
arr = [2 3 4 5 6 7 8 9]
arr = [2 4 6 8]
arr = [0.  0.2 0.4 0.6 0.8]
arr = [1 1 1 1 1 1 1 1 1 1]


`np.linspace()` returns `n` evenly spaced numbers over a specified interval, including both the `start` and `stop` values.

In [6]:
start, stop, n = 0, 1, 5

arr = np.linspace(start, stop, n)
print(f"arr = {arr}")

arr = np.linspace(start, stop, n, endpoint=False)
print(f"arr = {arr}")

arr, step = np.linspace(start, stop, n, retstep=True)
print(f"arr = {arr}, stepsize = {step}")

arr = np.linspace(start, stop, n, dtype=int)
print(f"arr = {arr}")

arr = [0.   0.25 0.5  0.75 1.  ]
arr = [0.  0.2 0.4 0.6 0.8]
arr = [0.   0.25 0.5  0.75 1.  ], stepsize = 0.25
arr = [0 0 0 0 1]


We have a few more constructors that generate special arrays of given shapes

In [7]:
print("nd array with all zeros")
m = np.zeros((3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with all zeros")
m = np.ones((3, 4))
print(m)
print(f"Default data type = {m.dtype}\n")

print("nd array with all same value")
value = 7
m = np.full((3, 4), value)
print(m)
print(f"Default data type = {m.dtype}\n")

nd array with all zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Default data type = float64

nd array with all zeros
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Default data type = float64

nd array with all same value
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Default data type = int64



#### Numpy random module

`np.random` is NumPy’s random number generation module, used for creating random numbers, arrays, distributions, shuffling, and more.

`np.random.rand()` gives random number between 0 & 1.

In [8]:
m = np.random.rand(3, 4) # gives a 2d array
print(m, "\n")
m = np.random.rand(3) # gievs a 1d array
print(m, "\n")
m = np.random.rand() # gives a scalar
print(m, "\n")

[[0.94236619 0.05570745 0.08391917 0.30121719]
 [0.38280329 0.03658042 0.75049842 0.90810242]
 [0.99987492 0.3210742  0.25675405 0.59817496]] 

[0.23206661 0.91664202 0.37978639] 

0.8269928871571377 



`np.random.randint()` gives random ints in given range.

In [9]:
m = np.random.randint(1, 7, size=(3, 4)) # gives a 2d array
print(m, "\n")
m = np.random.randint(1, 7, size=(3)) # gives a 1d array
print(m, "\n")
m = np.random.randint(1, 7) # gives a scalar
print(m, "\n")

[[1 6 4 5]
 [2 1 5 4]
 [1 4 1 2]] 

[1 2 4] 

5 



`np.random.choice()` picks random elements from given array (with or without replacements).

In [10]:
m = np.random.choice(100, size=(5), replace=False)
print(m, "\n")
m = np.random.choice([5, 2, 1, 4], size=(5), replace=True)
print(m, "\n")

[29 41 38 44 98] 

[2 4 2 1 5] 



## Making changes in array

#### Indexing in arrays

In [11]:
arr = np.array(
    [
        [11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34]
    ]
)
print(arr, "\n")

print("Dimensions of the array: ",arr.shape) # (3, 4)

# using indexing to print elements individually
print("\nUsing [i][j] notation")
for i in range (arr.shape[0]):
    for j in range (arr.shape[1]):
        print(arr[i][j], end = "  ")
    print("")

print("\nUsing [i, j] notation")
for i in range (arr.shape[0]):
    for j in range (arr.shape[1]):
        print(arr[i, j], end = "  ")
    print("")

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] 

Dimensions of the array:  (3, 4)

Using [i][j] notation
11  12  13  14  
21  22  23  24  
31  32  33  34  

Using [i, j] notation
11  12  13  14  
21  22  23  24  
31  32  33  34  


In [12]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(a)                # print the whole array
print(a[2])             # print the 3rd element
print(a[2], a[3], a[4]) # print the 3rd, 4th and 5th elements
print()
print(a[2:5])           # print a subarray having 3rd, 4th and 5th elements
print(a[2:])            # print the 3rd and onwards
print(a[:5])            # print the 1st, 2nd, 3rd, 4th and 5th element
print(a[0:7:2])         # print the 1st, 3rd, 5th and 7th element
print()
print(a[:])             # print the whole array
print(a[::])            # print the whole array
print(a[::-1])          # print the whole array in reverse

[10 20 30 40 50 60 70 80 90]
30
30 40 50

[30 40 50]
[30 40 50 60 70 80 90]
[10 20 30 40 50]
[10 30 50 70]

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]
[90 80 70 60 50 40 30 20 10]


In [13]:
arr = np.array(
    [
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25],
        [31, 32, 33, 34, 35],
        [41, 42, 43, 44, 45],
        [51, 52, 53, 54, 55],
    ]
)
print("Dimensions of the array: ",arr.shape) # (5, 5)
print("arr = \n", arr)

# to get a specific row
print("\nPrinting Specific Rows")
print(arr[0])
print(arr[2, :])

# to get a specific column
print("\nPrinting Specific Cols")
print(arr[:, 0])
print(arr[:, 2])

# to get a specific sub-matrices
print("\nPrinting Specific submatrices")
print(arr[0:2, 1:3])

# to get a specific element
print("\nPrinting Specific element")
print(arr[2, 3])

# to get a specific elements
print("\nPrinting Specific subarray")
print(arr[[1, 2, 3], [2, 3, 4]])

Dimensions of the array:  (5, 5)
arr = 
 [[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]

Printing Specific Rows
[11 12 13 14 15]
[31 32 33 34 35]

Printing Specific Cols
[11 21 31 41 51]
[13 23 33 43 53]

Printing Specific submatrices
[[12 13]
 [22 23]]

Printing Specific element
34

Printing Specific subarray
[23 34 45]


#### Making a copy of an array

There are two types of copies : Shallow Copy & Deep Copy

- Shallow Copy: When two different variables point to the same memory location
- Deep Copy: When two different variables point to different memory location

In [29]:
# Initializing lists
og = [0, 1, 2, 3, 4, 5]

sh = og             # this creates a shallow copy

dp1 = og[:]         # this creates a deep copy

dp2 = og.copy()     # this creates a deep copy
dp3 = list(og)      # this creates a deep copy

print("Before:")
print(f"og  = {og}")
print(f"sh  = {sh}")
print(f"dp1 = {dp1}")
print(f"dp2 = {dp2}")
print(f"dp3 = {dp3}")

# making changes
og[1] = 100
sh[2] = 200
dp1[3] = 300
dp2[4] = 400
dp3[5] = 500

print("\nAfter:")
print(f"og  = {og}")
print(f"sh  = {sh}")
print(f"dp1 = {dp1}")
print(f"dp2 = {dp2}")
print(f"dp3 = {dp3}")

Before:
og  = [0, 1, 2, 3, 4, 5]
sh  = [0, 1, 2, 3, 4, 5]
dp1 = [0, 1, 2, 3, 4, 5]
dp2 = [0, 1, 2, 3, 4, 5]
dp3 = [0, 1, 2, 3, 4, 5]

After:
og  = [0, 100, 200, 3, 4, 5]
sh  = [0, 100, 200, 3, 4, 5]
dp1 = [0, 1, 2, 300, 4, 5]
dp2 = [0, 1, 2, 3, 400, 5]
dp3 = [0, 1, 2, 3, 4, 500]


In [30]:
# Initializing arrays
og = np.array([0, 1, 2, 3, 4, 5])

sh1 = og            # this creates a shallow copy
sh2 = og[:]         # this creates a shallow copy

dp1 = og.copy()     # this creates a deep copy
dp2 = np.array(og)  # this creates a deep copy

print("Before:")
print(f"og  = {og}")
print(f"sh1 = {sh1}")
print(f"sh2 = {sh2}")
print(f"dp1 = {dp1}")
print(f"dp2 = {dp2}")

# making changes
og[1] = 100
sh1[2] = 200
sh2[3] = 300
dp1[4] = 400
dp2[5] = 500

print("\nAfter:")
print(f"og  = {og}")
print(f"sh1 = {sh1}")
print(f"sh2 = {sh2}")
print(f"dp1 = {dp1}")
print(f"dp2 = {dp2}")

Before:
og  = [0 1 2 3 4 5]
sh1 = [0 1 2 3 4 5]
sh2 = [0 1 2 3 4 5]
dp1 = [0 1 2 3 4 5]
dp2 = [0 1 2 3 4 5]

After:
og  = [  0 100 200 300   4   5]
sh1 = [  0 100 200 300   4   5]
sh2 = [  0 100 200 300   4   5]
dp1 = [  0   1   2   3 400   5]
dp2 = [  0   1   2   3   4 500]


#### Reshaping

In [16]:
a = [[6, 1, 8, 0], [3, 9, 8, 7]]
# print(a)
before = np.array(a)
print(before)
print(f"shape = {before.shape}\ndim = {before.ndim}\n")

after = before.reshape((4,2)) # it is Not the same as transpose
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((1, 8)) # it still is 2D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((8, 1)) # it still is 2D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((8,)) # now it is 1D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

after = before.reshape((2, 2, 2)) # now it is 3D
print(after)
print(f"shape = {after.shape}\ndim = {after.ndim}\n")

# after = before.reshape((2, 3))
# this causes error as the no of elements dont match

[[6 1 8 0]
 [3 9 8 7]]
shape = (2, 4)
dim = 2

[[6 1]
 [8 0]
 [3 9]
 [8 7]]
shape = (4, 2)
dim = 2

[[6 1 8 0 3 9 8 7]]
shape = (1, 8)
dim = 2

[[6]
 [1]
 [8]
 [0]
 [3]
 [9]
 [8]
 [7]]
shape = (8, 1)
dim = 2

[6 1 8 0 3 9 8 7]
shape = (8,)
dim = 1

[[[6 1]
  [8 0]]

 [[3 9]
  [8 7]]]
shape = (2, 2, 2)
dim = 3



## Doing mathematical operations in NumPy Arrays

#### Elementwise Operations

In [17]:
# array with scalar
a = np.array([1, 2, 3, 4])
print(a)
print(a, "+ 2 = ", a + 2)
print(a, "- 2 = ", a - 2)
print(a, "* 2 = ", a * 2)
print(a, "/ 2 = ", a / 2)
print(a, "% 2 = ", a % 2)
print(a, "// 2 = ", a // 2)
print(a, "** 2 = ", a ** 2)

[1 2 3 4]
[1 2 3 4] + 2 =  [3 4 5 6]
[1 2 3 4] - 2 =  [-1  0  1  2]
[1 2 3 4] * 2 =  [2 4 6 8]
[1 2 3 4] / 2 =  [0.5 1.  1.5 2. ]
[1 2 3 4] % 2 =  [1 0 1 0]
[1 2 3 4] // 2 =  [0 1 1 2]
[1 2 3 4] ** 2 =  [ 1  4  9 16]


In [18]:
# array with array
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 2, 1])
print(a, " + ", b, " = ", a + b)
print(a, " - ", b, " = ", a - b)
print(a, " * ", b, " = ", a * b)
print(a, " / ", b, " = ", a / b)

[1 2 3 4]  +  [1 2 2 1]  =  [2 4 5 5]
[1 2 3 4]  -  [1 2 2 1]  =  [0 0 1 3]
[1 2 3 4]  *  [1 2 2 1]  =  [1 4 6 4]
[1 2 3 4]  /  [1 2 2 1]  =  [1.  1.  1.5 4. ]


#### Boolean Operations

In [19]:
a = np.array([[6, 1, 8], [3, 9, 8], [5, 2, 1]])
print(a, "\n")

print(a < 5)

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

[[False  True False]
 [ True False False]
 [False  True  True]]


In [20]:
a = np.array([[6, 1, 8], [3, 9, 8], [5, 2, 1]])
print(a, "\n")
print(a[a < 5]) # print all elements of `a` which are less than 5
print()
print(a[a > 10]) # print all elements of `a` which are greater than or equal to 5

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

[1 3 2 1]

[]


In [21]:
print(a, "\n")

# check for whole nd array
print(np.any(a >= 8), "\n")

# check in particular axis
print(np.any(a >= 8, axis = 0), "\n") # 0 means column
print(np.any(a >= 8, axis = 1), "\n") # 1 means row

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

True 

[False  True  True] 

[ True  True False] 



In [22]:
print(a, "\n")

# check for whole nd array
print(np.all(a >= 3), "\n")

# check in particular axis
print(np.all(a >= 3, axis = 0), "\n") # 0 means column
print(np.all(a >= 3, axis = 1), "\n") # 1 means row

[[6 1 8]
 [3 9 8]
 [5 2 1]] 

False 

[ True False False] 

[False  True False] 



In [23]:
a = np.array([1, 2, 3, 4, 5])
indices = np.where(a % 2 == 0)
print(indices)

a = np.array([ 1,  2,  3,  4,  5])
b = np.array([10, 20, 30, 40, 50])
result = np.where(a > 3, a, b) # WHERE (a > 3), pick elements from a ELSE, pick elements from b.
print(result)

a = np.array([0, -1, 2, -3, 4])
cleaned = np.where(a > 0, a, 0) # WHERE (a > 0), pick elements from a ELSE, pick 0.
print(cleaned)

(array([1, 3]),)
[10 20 30  4  5]
[0 0 2 0 4]


#### Statistical Operation

In [24]:
stats = np.array([[6, 1, 8, 0], [3, 9, 8, 7]])
print(stats, "\n")

print(np.min(stats))
print(np.min(stats, axis = 0))
print(np.min(stats, axis = 1), "\n")

print(np.max(stats))
print(np.max(stats, axis = 0))
print(np.max(stats, axis = 1), "\n")

print(np.sum(stats))
print(np.sum(stats, axis = 0))
print(np.sum(stats, axis = 1), "\n")


[[6 1 8 0]
 [3 9 8 7]] 

0
[3 1 8 0]
[0 3] 

9
[6 9 8 7]
[8 9] 

42
[ 9 10 16  7]
[15 27] 

